import Header from "./components/Header";

export const metadata = {
    title: "Create Next App",
    description: "Generated by created next app"
};

export default function Layout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            </head>
            <body>
                <header 
                    style={{
                        backgroundColor:'tomato',
                        padding: '1rem'
                    }}
                >
                    <Header />
                </header>

                <main>
                    {children}
                </main>

                <footer 
                    style={{
                        backgroundColor:'lightseagreen',
                        padding: '1rem'
                    }}>HEADER
                </footer>
            </body>
        </html>
    );
}